name: ci

on:
  push:
    branches:
      - "!main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js for cache
        uses: actions/setup-node@v4
        with:
          node-version: "21 "
          cache: "npm" #cache for dependencies and next js build

      - name: Install modules
        run: npm install

      - name: Build project
        run: npm run build

      - name: run e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run dev
          wait-on: "http://localhost:8080"
